In [ ]:
********************************************************************************************************************************

## 1. How would you describe TensorFlow in a short sentence? What are its main features? Can you name other popular Deep Learning libraries?

TensorFlow is an open-source library developed by Google primarily for deep learning applications. It also supports traditional machine learning. TensorFlow was originally developed for large numerical computations without keeping deep learning in mind. However, it proved to be very useful for deep learning development as well, and therefore Google open-sourced it.

TensorFlow accepts data in the form of multi-dimensional arrays of higher dimensions called tensors. Multi-dimensional arrays are very handy in handling large amounts of data.

TensorFlow works on the basis of data flow graphs that have nodes and edges. As the execution mechanism is in the form of graphs, it is much easier to execute TensorFlow code in a distributed manner across a cluster of computers while using GPUs.

In [ ]:
********************************************************************************************************************************

## 2. Is TensorFlow a drop-in replacement for NumPy? What are the main differences between the two?

I  think it may be worth adding a bit more of information, although it is easy to find about it just searching around a bit.

NumPy and TensorFlow are actually very similar in many respects. Both are, essentially, array manipulation libraries, built around the concept of tensors (or nd-arrays, in NumPy terms). Originally, in TensorFlow 0.x and 1.x, there was only "graph mode", with all values being "symbolic tensors" that did not have a specific value until one was fed at a later point... It was a bit confusing and quite different from NumPy. Nowadays "graph mode" still exists but, for the most part, TensorFlow 2.x works in "eager mode", where each tensor has a specific value. This makes it more similar to NumPy, so the differences may seem subtle. So maybe we can draft a list with some of the most significant points.

NumPy was developed as a full-fledged open source tensor algebra package for Python that could rival MATLAB and the likes. It is a Python library with a long history and plenty of functionality, either directly in it or built around it (see SciPy and different scikits). TensorFlow was developed by Google much more recently specifically for the purpose of building machine learning models (although you could use it for many other tasks), continuing the ideas from the (now discontinued) Theano library. Although TensorFlow is most commonly used with Python, it can be used in C/C++ and other languages too, which is important because it allows you to train a model in Python and then integrate it in an existing application written in another language.
A main selling point of TensorFlow is that it can automatically differentiate computations. This is an essential feature for deep learning, that uses gradient-based optimization (backpropagation), and it means that you can pretty much just write whatever you want to compute and TensorFlow will figure out the gradients by itself. There are things like Autograd or JAX for NumPy, but they are not as powerful as TensorFlow automatic differentiation, which actually maintains a computation graph structure under the hood (the name "TensorFlow" refers to the tensors and their gradients "flowing" through the computation graph).
TensorFlow offers GPU computation with CUDA out of the box. Again there are things like CuPy for NumPy, but it is not part of the library itself.
TensorFlow integrates a lot more functionality that is not strictly array manipulation into the library itself, like image manipulation and common neural network utilities. NumPy tends to defer that kind of things to additional libraries like SciPy, making it more of an ecosystem and less monolithic. TensorFlow has some of that too, like TensorFlow Probability or TensorFlow Graphics, but it is not too developed yet.
TensorFlow offers a bunch of useful stuff if you are doing machine learning, like training checkpoints, distributed training, TensorBoard, TensorFlow Serving, etc. It also integrates better (or at all) with inference platforms and standards like TensorRT, Google Coral, ONNX and that kind of stuff.
NumPy generally integrates better with the "traditional" Python scientific stack, like Jupyter, Matplotlib, Pandas, dask, xarray, etc. There are pretty good libraries to do machine learning with NumPy too, like scikit-learn or Chainer, which are perfectly good if you only need to work in Python.
TensorFlow and NumPy also work reasonably well together, specially in eager mode, where any TensorFlow tensor can be directly converted to a NumPy array.

In [ ]:
********************************************************************************************************************************

## 3. Do you get the same result with tf.range(10) and tf.constant(np.arange(10))?

In [3]:
import tensorflow as tf
import numpy as np

def main():

    s = tf.constant(np.random.rand(20))
    rate = 10
    s1 = np.arange(0, tf.shape(s)[0], rate)
    s2 = tf.range(0, tf.shape(s)[0], rate).numpy()

    print(s1)
    print(s2)

if __name__ == '__main__':
    main()

[ 0 10]
[ 0 10]


In [ ]:
********************************************************************************************************************************

## 4. Can you name six other data structures available in TensorFlow, beyond regular tensors?

In [5]:
# Scalars or Rank-0 tensors:

x = np.array(34)
print(x)
print(x.ndim)

34
0


In [6]:
# Vectors or Rank-1 tensors:

y = np.array([34, 4, 7, 21, 8])
print(y)
print(y.ndim)

[34  4  7 21  8]
1


In [7]:
# Matrices or Rank-2 tensors:

z = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])
print(z)
print(z.ndim)

[[ 5 78  2 34  0]
 [ 6 79  3 35  1]
 [ 7 80  4 36  2]]
2


In [9]:
# Cube or Rank-3 tensors:

w = np.array([[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]])
print(w)
print(w.ndim)

[[[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]]
3


In [ ]:
********************************************************************************************************************************

## 5. A custom loss function can be defined by writing a function or by subclassing the keras.losses.Loss class. When would you use each option?

## Probabilistic losses

1. BinaryCrossentropy class
2. CategoricalCrossentropy class
3. SparseCategoricalCrossentropy class
4. Poisson class
5. binary_crossentropy function
6. categorical_crossentropy function
7. sparse_categorical_crossentropy function
8. poisson function
9. KLDivergence class
10. kl_divergence function

## Regression losses

1. MeanSquaredError class
2. MeanAbsoluteError class
3. MeanAbsolutePercentageError class
4. MeanSquaredLogarithmicError class
5. CosineSimilarity class
6. mean_squared_error function
7. mean_absolute_error function
8. mean_absolute_percentage_error function
9. mean_squared_logarithmic_error function
10. cosine_similarity function
11. Huber class
12. huber function
13. LogCosh class
14. log_cosh function

## Hinge losses for "maximum-margin" classification

1. Hinge class
2. SquaredHinge class
3. CategoricalHinge class
4. hinge function
5. squared_hinge function
6. categorical_hinge function

In [ ]:
********************************************************************************************************************************

## 6. Similarly, a custom metric can be defined in a function or a subclass of keras.metrics.Metric. When would you use each option?

## Accuracy metrics

1. Accuracy class
2. BinaryAccuracy class
3. CategoricalAccuracy class
4. SparseCategoricalAccuracy class
5. TopKCategoricalAccuracy class
6. SparseTopKCategoricalAccuracy class
7. Probabilistic metrics
8. BinaryCrossentropy class
9. CategoricalCrossentropy class
10. SparseCategoricalCrossentropy class
11. KLDivergence class
12. Poisson class

## Regression metrics

1. MeanSquaredError class
2. RootMeanSquaredError class
3. MeanAbsoluteError class
4. MeanAbsolutePercentageError class
5. MeanSquaredLogarithmicError class
6. CosineSimilarity class
7. LogCoshError class

## Classification metrics based on True/False positives & negatives

1. AUC class
2. Precision class
3. Recall class
4. TruePositives class
5. TrueNegatives class
6. FalsePositives class
7. FalseNegatives class
8. PrecisionAtRecall class
9. SensitivityAtSpecificity class
10. SpecificityAtSensitivity class

## Image segmentation metrics

1. MeanIoU class
2. Hinge metrics for "maximum-margin" classification
3. Hinge class
4. SquaredHinge class
5. CategoricalHinge class

In [ ]:
********************************************************************************************************************************

## 7. When should you create a custom layer versus a custom model?

If you are building a new model architecture using existing keras/tf layers then build a custom model. If you are implementing your own custom tensor operations with in a layer, then build a custom layer.

In [ ]:
********************************************************************************************************************************

## 8. What are some use cases that require writing your own custom training loop?

For people getting started with deep learning, the Keras toolbox has no equal. It has everything you need, with the confusing low-level stuff kept to a minimum. The API is very intuitive and makes you focus on the important bits of designing a network, allowing for fast experimentation without much hassle. As an example, the network used in this guide is specified and trained in less than 25 lines of Python code.

There will come times, however, when the ease-of-use of basic Keras functions becomes limiting. Many more advanced neural network training schemes and loss functions become unnecessarily complicated to code up in native Keras. In this guide, I aim to show how the base Keras way of training a neural network can be broken up in its underlying parts, opening up the possibility to change each part as a user sees fit. I do not incorporate any of these custom parts in the example; this guide only aims to give you the tools to experiment more by yourself.

In [ ]:
********************************************************************************************************************************

## 9. Can custom Keras components contain arbitrary Python code, or must they be convertible to TF Functions?

By default tensorflow 2.1 runs in eager mode which is useful for development and debugging. Performance can be boosted by wrapping your functions in `tf.function` which compiles a tensorflow graph which the framework can execute efficiently.

There are several ways to wrap portions of your code as a `tf.function` . In the demonstrated toy example, the best performance was observed with the case when the entire training happened inside a tf.function.

However in real world use case there are several factors at play — whether all of the dataset is in memory or streamed from disk / network , computational load of the model, whether gpu / multiple gpus are being used, how the shapes of your training data varies etc. One should experiment to figure how the `tf.function` can be used most efficiently.

In [ ]:
********************************************************************************************************************************

## 10. What are the main rules to respect if you want a function to be convertible to a TF Function?

A Function runs your program in a TensorFlow Graph. However, a tf.Graph cannot represent all the things that you'd write in an eager TensorFlow program. For instance, Python supports polymorphism, but tf.Graph requires its inputs to have a specified data type and dimension. Or you may perform side tasks like reading command-line arguments, raising an error, or working with a more complex Python object; none of these things can run in a tf.Graph.

Function bridges this gap by separating your code in two stages:

1) In the first stage, referred to as "tracing", Function creates a new tf.Graph. Python code runs normally, but all TensorFlow operations (like adding two Tensors) are deferred: they are captured by the tf.Graph and not run.

2) In the second stage, a tf.Graph which contains everything that was deferred in the first stage is run. This stage is much faster than the tracing stage.

Depending on its inputs, Function will not always run the first stage when it is called. See "Rules of tracing" below to get a better sense of how it makes that determination. Skipping the first stage and only executing the second stage is what gives you TensorFlow's high performance.

When Function does decide to trace, the tracing stage is immediately followed by the second stage, so calling the Function both creates and runs the tf.Graph. Later you will see how you can run only the tracing stage with get_concrete_function.

In [ ]:
********************************************************************************************************************************

## 11. When would you need to create a dynamic Keras model? How do you do that? Why not make all your models dynamic?

Keras is a neural network Application Programming Interface (API) for Python that is tightly integrated with TensorFlow, which is used to build machine learning models. Keras’ models offer a simple, user-friendly way to define a neural network, which will then be built for you by TensorFlow. 

In [ ]:
********************************************************************************************************************************